# Replace 'ae-boilerplate' with your application name
application: ae-boilerplate
version: 1 
runtime: python
api_version: 1

default_expiration: "30d"

builtins:
- datastore_admin: on

handlers:
# Cron jobs and other secured things
- url: /services.*
  script: services.py
  login: admin

# If authenticated user, AE will ask for login and redirect 
- url: /account
  script: app.py
  login: required

# Handler for login for restricted area 
- url: /_ah/login_required
  script: app.py

# html-5 boilerplate redirects to /static/... 
- url: /apple-touch-icon\.png
  mime_type: image/png
  static_files: static/apple-touch-icon.png
  upload: static/apple-touch-icon.png

- url: /favicon\.ico
  mime_type: image/png
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /(robots\.txt|humans\.txt|crossdomain\.xml)
  static_files: static/\1
  upload: static/(robots\.txt|humans\.txt|crossdomain\.xml)

- url: /images/(.*\.(gif|png|jpg))
  static_files: static/images/\1
  upload: static/images/(.*\.(gif|png|jpg))
  
- url: /swf/(.*\.swf)
  static_files: static/swf/\1
  upload: static/swf/(.*\.swf)

- url: /css/(.*\.css)
  mime_type: text/css
  static_files: static/css/\1
  upload: static/css/(.*\.css)

- url: /js/(.*\.js)
  mime_type: text/javascript
  static_files: static/js/\1
  upload: static/js/(.*\.js)

- url: /(.*\.html)
  mime_type: text/html
  static_files: static/\1
  upload: static/(.*\.html)
    
# All other requests go to the main app
- url: /.*
  script: app.py
